version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-02 to 2020-01-13 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-20 to 2020-06-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-06-08 to 2020-10-19 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv.gz

  generate_study_population_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-10-26 to 2021-03-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv.gz

  generate_study_population_5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-03-08 to 2021-07-19 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/in*.csv.gz

  generate_study_population_6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-07-26 to 2021-12-27 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/i*.csv.gz


  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3, generate_study_population_4, generate_study_population_5, generate_study_population_6]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv


  run_model_dva:
    run: stata-mp:latest analysis/model_DVA.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_dva1: output/dva_plot1.png
        model_dva2: output/dva_plot2.png

  run_model_intdis:
    run: stata-mp:latest analysis/model_intdis.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_intdis1: output/intdis_plot1.png
        model_intdis2: output/intdis_plot2.png

  run_model_RCGPsafeguard:
    run: stata-mp:latest analysis/model_RCGPsafeguard.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_RCGPsafeguard1: output/RCGPsafeguard_plot1.png
        model_RCGPsafeguard2: output/RCGPsafeguard_plot2.png

  run_model_safeguard:
    run: stata-mp:latest analysis/model_safeguard.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_safeguard1: output/safeguard_plot1.png
        model_safeguard2: output/safeguard_plot2.png

  run_model_opioid:
    run: stata-mp:latest analysis/model_opioid.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_opioid1: output/opioid_plot1.png
        model_opioid2: output/opioid_plot2.png

  run_model_misuse:
    run: stata-mp:latest analysis/model_misuse.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_misuse1: output/misuse_plot1.png
        model_misuse2: output/misuse_plot2.png