version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-02 to 2020-01-13 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-20 to 2020-06-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-06-08 to 2020-10-19 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv.gz

  generate_study_population_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-10-26 to 2021-03-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv.gz

  generate_study_population_5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-03-08 to 2021-06-14 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/in*.csv.gz

  generate_study_population_6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-06-21 to 2021-09-27 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/i*.csv.gz


  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3, generate_study_population_4, generate_study_population_5, generate_study_population_6]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv


  subgroup_setup:
    run: stata-mp:latest analysis/subgroup_data_setup.do
    needs: [generate_measures]
    outputs:
      highly_sensitive:
        subgroup1: output/measure_dvafemale_rate.dta
        subgroup2: output/measure_dvamale_rate.dta
        subgroup3: output/measure_intdissub14_rate.dta
        subgroup4: output/measure_intdisover14_rate.dta
        subgroup5: output/measure_RCGPsafeguard_rate.dta


  model_alcmisuse:
    run: stata-mp:latest analysis/model.do alcmisuse
    needs:
    - generate_measures
    outputs:
      highly_sensitive:
        results1: output/alcmisuse_RR_LD1.dta
        results2: output/alcmisuse_RD_LD1.dta
        results3: output/alcmisuse_RR_LD2.dta
        results4: output/alcmisuse_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/alcmisuse_diagnostics1.svg
        diagnostics2: output/diagnostics/alcmisuse_diagnostics2.svg
        plot1: output/alcmisuse_plot1.svg
        plot2: output/alcmisuse_plot2.svg

  model_drugmisuse:
    run: stata-mp:latest analysis/model.do drugmisuse
    needs:
    - generate_measures
    outputs:
      highly_sensitive:
        results1: output/drugmisuse_RR_LD1.dta
        results2: output/drugmisuse_RD_LD1.dta
        results3: output/drugmisuse_RR_LD2.dta
        results4: output/drugmisuse_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/drugmisuse_diagnostics1.svg
        diagnostics2: output/diagnostics/drugmisuse_diagnostics2.svg
        plot1: output/drugmisuse_plot1.svg
        plot2: output/drugmisuse_plot2.svg

  model_opioid:
    run: stata-mp:latest analysis/model.do opioid
    needs:
    - generate_measures
    outputs:
      highly_sensitive:
        results1: output/opioid_RR_LD1.dta
        results2: output/opioid_RD_LD1.dta
        results3: output/opioid_RR_LD2.dta
        results4: output/opioid_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/opioid_diagnostics1.svg
        diagnostics2: output/diagnostics/opioid_diagnostics2.svg
        plot1: output/opioid_plot1.svg
        plot2: output/opioid_plot2.svg

  model_dvafemale:
    run: stata-mp:latest analysis/model.do dvafemale
    needs:
    - generate_measures
    outputs:
      highly_sensitive:
        results1: output/dvafemale_RR_LD1.dta
        results2: output/dvafemale_RD_LD1.dta
        results3: output/dvafemale_RR_LD2.dta
        results4: output/dvafemale_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/dvafemale_diagnostics1.svg
        diagnostics2: output/diagnostics/dvafemale_diagnostics2.svg
        plot1: output/dvafemale_plot1.svg
        plot2: output/dvafemale_plot2.svg

  model_dvamale:
    run: stata-mp:latest analysis/model.do dvamale
    needs:
    - subgroup_setup
    outputs:
      highly_sensitive:
        results1: output/dvamale_RR_LD1.dta
        results2: output/dvamale_RD_LD1.dta
        results3: output/dvamale_RR_LD2.dta
        results4: output/dvamale_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/dvamale_diagnostics1.svg
        diagnostics2: output/diagnostics/dvamale_diagnostics2.svg
        plot1: output/dvamale_plot1.svg
        plot2: output/dvamale_plot2.svg

  model_intdissub14:
    run: stata-mp:latest analysis/model.do intdissub14
    needs:
    - subgroup_setup
    outputs:
      highly_sensitive:
        results1: output/intdissub14_RR_LD1.dta
        results2: output/intdissub14_RD_LD1.dta
        results3: output/intdissub14_RR_LD2.dta
        results4: output/intdissub14_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/intdissub14_diagnostics1.svg
        diagnostics2: output/diagnostics/intdissub14_diagnostics2.svg
        plot1: output/intdissub14_plot1.svg
        plot2: output/intdissub14_plot2.svg

  model_intdisover14:
    run: stata-mp:latest analysis/model.do intdisover14
    needs:
    - subgroup_setup
    outputs:
      highly_sensitive:
        results1: output/intdisover14_RR_LD1.dta
        results2: output/intdisover14_RD_LD1.dta
        results3: output/intdisover14_RR_LD2.dta
        results4: output/intdisover14_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/intdisover14_diagnostics1.svg
        diagnostics2: output/diagnostics/intdisover14_diagnostics2.svg
        plot1: output/intdisover14_plot1.svg
        plot2: output/intdisover14_plot2.svg


  model_RCGPsafeguard:
    run: stata-mp:latest analysis/model.do RCGPsafeguard
    needs:
    - subgroup_setup
    outputs:
      highly_sensitive:
        results1: output/RCGPsafeguard_RR_LD1.dta
        results2: output/RCGPsafeguard_RD_LD1.dta
        results3: output/RCGPsafeguard_RR_LD2.dta
        results4: output/RCGPsafeguard_RD_LD2.dta
      moderately_sensitive:
        diagnostics1: output/diagnostics/RCGPsafeguard_diagnostics1.svg
        diagnostics2: output/diagnostics/RCGPsafeguard_diagnostics2.svg
        plot1: output/RCGPsafeguard_plot1.svg
        plot2: output/RCGPsafeguard_plot2.svg

  combine_results:
    run: stata-mp:latest analysis/combine_results.do
    needs:
    - model_alcmisuse
    - model_drugmisuse
    - model_opioid
    - model_dvafemale
    - model_dvamale
    - model_intdissub14
    - model_intdisover14
    - model_RCGPsafeguard
    outputs:
      moderately_sensitive:
        results: output/CITS_results.csv