version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-02 to 2020-01-13 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-20 to 2020-06-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-06-08 to 2020-10-19 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv.gz

  generate_study_population_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-10-26 to 2021-03-01 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv.gz

  generate_study_population_5:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-03-08 to 2021-06-14 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/in*.csv.gz

  generate_study_population_6:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-06-21 to 2021-09-27 by week" --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/i*.csv.gz


  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3, generate_study_population_4, generate_study_population_5, generate_study_population_6]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv


  run_subgroup_setup:
    run: stata-mp:latest analysis/subgroup_data_setup.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        subgroup1: output/dva_female.dta
        subgroup2: output/dva_male.dta
        subgroup3: output/dva_all.dta
        subgroup4: output/intdis_sub14.dta
        subgroup5: output/intdis_over14.dta
        subgroup6: output/intdis_all.dta
        subgroup7: output/RCGPsafeguard_sub18.dta
        subgroup8: output/CovidNewCaseCounts.dta

  run_model_dva_female:
    run: stata-mp:latest analysis/model_DVA_female.do
    needs: [run_subgroup_setup]
    outputs:
      moderately_sensitive:
        model_dva_female0: output/CITS_dva.xlsx
        model_dva_female1: output/dva_female2.dta
        model_dva_female2: output/dva_female2_ld1.dta
        model_dva_female3: output/dva_ratioLoess_f1.svg
        model_dva_female4: output/diagnostics/dva_diagnostics_f1.svg
        model_dva_female5: output/dva_female_plot1.svg
        model_dva_female6: output/dva_female2_ld2.dta
        model_dva_female7: output/dva_ratioLoess_f2.svg
        model_dva_female8: output/diagnostics/dva_diagnostics_f2.svg
        model_dva_female9: output/dva_female_plot2.svg

  run_model_dva_male:
    run: stata-mp:latest analysis/model_DVA_male.do
    needs: [run_subgroup_setup]
    outputs:
      moderately_sensitive:
        model_dva_male0: output/CITS_dva.xlsx
        model_dva_male1: output/dva_male2.dta
        model_dva_male2: output/dva_male2_ld1.dta
        model_dva_male3: output/dva_ratioLoess_m1.svg
        model_dva_male4: output/diagnostics/dva_diagnostics_m1.svg
        model_dva_male5: output/dva_male_plot1.svg
        model_dva_male6: output/dva_male2_ld2.dta
        model_dva_male7: output/dva_ratioLoess_m2.svg
        model_dva_male8: output/diagnostics/dva_diagnostics_m2.svg
        model_dva_male9: output/dva_male_plot2.svg

  run_model_intdis:
    run: stata-mp:latest analysis/model_intdis.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_intdis1: output/intdis_plot1.pdf
        model_intdis2: output/intdis_plot2.pdf

  run_model_RCGPsafeguard:
    run: stata-mp:latest analysis/model_RCGPsafeguard.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_RCGPsafeguard1: output/RCGPsafeguard_plot1.pdf
        model_RCGPsafeguard2: output/RCGPsafeguard_plot2.pdf

  run_model_safeguard:
    run: stata-mp:latest analysis/model_safeguard.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_safeguard1: output/safeguard_plot1.pdf
        model_safeguard2: output/safeguard_plot2.pdf

  run_model_opioid:
    run: stata-mp:latest analysis/model_opioid.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_opioid1: output/opioid_plot1.pdf
        model_opioid2: output/opioid_plot2.pdf

  run_model_misuse:
    run: stata-mp:latest analysis/model_misuse.do
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        model_misuse1: output/misuse_plot1.pdf
        model_misuse2: output/misuse_plot2.pdf